### ISSUE TITLE
ObjectiveC generation not working

### ISSUE THREAD

**Issue by Arcnor** [ochafik/nativelibs4java#191]
I've tried the example from the ObjectiveC wiki page to generate bindings for AppKit, Foundation and CoreFoundation (leaving out CoreFoundation gives the same error message). A .jar is generated, but lots of errors are thrown. don't know if it's because I need to configure anything at all, or a bug in jnaerator (cloned git repo today and uses precompiled bin/jnaerator.jar)

I'm using Java Mac OSX 10.6.6

Error log is here: https://gist.github.com/1300774

Hope this helps!

**Comment by ochafik** [comment]
This issue was moved to ochafik/JNAerator#18
