### ISSUE TITLE
No optimization for Scala parallelized collections

### ISSUE THREAD

**Issue by fdietze** [ochafik/nativelibs4java#199]
It seems like there is no optimization for the parallelized collections in Scala.

This is optimized:
(0 until 1000).map

While this is not:
(0 until 1000).par.map

Whats the easiest way to get the parallelized collections optimized? The CL-Collections?

Thanks for this great compiler plugin. It helped me a lot speeding up my existing project.

**Comment by ochafik** [comment]
This issue was moved to ochafik/Scalaxy#25
