### ISSUE TITLE
BridJ 0.6 regression compared to 0.6-SNAPSHOT

### ISSUE THREAD

**Issue by trandi** [ochafik/nativelibs4java#201]
As per the discussion here:
http://groups.google.com/group/nativelibs4java/browse_thread/thread/5baf2df02ad5425f?pli=1

There seem to have been a regression in the way the 0.6 version handles the loading of the library.

Here's the verbose output obtained with  BRIDJ_VERY_VERBOSE=1.

As already mentioned, the EXACT same configuration / code works with 0.6-SNAPSHOT (from the 24th of Oct) but if I replace the bridj jar with the 0.6 version (and this is the ONLY change), THEN I get this error :

------------------------------------------------------- 
 T E S T S 
------------------------------------------------------- 
Running com.markit.quic.dispatchapi.PRDCTest 
14-Nov-2011 14:42:20 org.bridj.BridJ log 
INFO: Embedded paths for library bridj : [org/bridj/lib/win64/ 
bridj.dll, lib/win64/bridj.dll] 
14-Nov-2011 14:42:20 org.bridj.BridJ log 
INFO: Loading library C:\Users\DAN\AppData\Local\Temp 
\bridj.dll6524064044671421676.dll 
14-Nov-2011 14:42:20 org.bridj.BridJ log 
INFO: Loaded library C:\Users\DAN\AppData\Local\Temp 
\bridj.dll6524064044671421676.dll 
14-Nov-2011 14:42:20 org.bridj.BridJ log 
INFO: Runtime for com.markit.quic.dispatchapi.QuicLib : 
org.bridj.CRuntime 
14-Nov-2011 14:42:20 org.bridj.AbstractBridJRuntime log 
INFO: Registering type com.markit.quic.dispatchapi.QuicLib 
14-Nov-2011 14:42:20 org.bridj.BridJ log 
INFO: Looking for library 'QuicDispatchCpp' in paths [D:/Program Files/ 
quic/quic/quic-platform/v3.10/bin, null, .,........ D:\Program Files 
\groovy-1.8.0\bin, D:\Program Files\maven\bin, D:\Program Files\apache- 
ant-1.8.1\bin, D:\cygwin\bin, D:\Program Files, D:\Program Files 
\Fortify 360 v2.6.5\bin, D:\Program Files\fortifyclient\bin, C: 
\progsDan\apache-ant-1.8.1\bin, D:\Program Files\Java\jdk1.6.0_25\jre 
\bin] 
14-Nov-2011 14:42:20 org.bridj.AbstractBridJRuntime log 
SEVERE: Method public static native 
org.bridj.Pointer<com.markit.quic.dispatchapi.bridj.IQuicDispatch> 
com.markit.quic.dispatchapi.QuicLib.QuicCreateDispatch() cannot be 
mapped : java.lang.RuntimeException: Library 'QuicDispatchCpp' was not 
loaded successfully from file 'D:\Program Files\quic\quic\quic-platform 
\v3.10\bin\QuicDispatchCpp.dll' 
java.lang.RuntimeException: Library 'QuicDispatchCpp' was not loaded 
successfully from file 'D:\Program Files\quic\quic\quic-platform 
\v3.10\bin\QuicDispatchCpp.dll' 
        at org.bridj.BridJ.getNativeLibrary(BridJ.java:854) 
        at org.bridj.BridJ.getNativeLibrary(BridJ.java:833) 
        at org.bridj.BridJ.getNativeLibrary(BridJ.java:451) 
        at org.bridj.CRuntime.register(CRuntime.java:333) 
        at org.bridj.CRuntime.register(CRuntime.java:246) 
        at org.bridj.BridJ.register(BridJ.java:286) 
        at org.bridj.BridJ.register(BridJ.java:155) 
        at com.markit.quic.dispatchapi.QuicLib.<clinit>(QuicLib.java: 
35) 
        at com.markit.quic.dispatchapi.Quic.<init>(Quic.java:25) 
        at com.markit.quic.dispatchapi.PRDCTest.test(PRDCTest.java:19) 
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
        at 
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java: 
39) 
        at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImp l.java: 
25) 
        at java.lang.reflect.Method.invoke(Method.java:597) 
        at org.junit.runners.model.FrameworkMethod 
$1.runReflectiveCall(FrameworkMethod.java:45) 
        at 
org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable. java: 
15) 
        at 
org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.j ava: 
42) 
        at 
org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.ja va: 
20) 
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java: 
263) 
        at 
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.ja va: 
68) 
        at 
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.ja va: 
47) 
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) 
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java: 
60) 
        at 
org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) 
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java: 
50) 
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java: 
222) 
        at org.junit.runners.ParentRunner.run(ParentRunner.java:300) 
        at 
org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java: 
62) 
        at 
org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(A bstractDirectoryTestSuite.java: 
140) 
        at 
org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(Abstract DirectoryTestSuite.java: 
127) 
        at org.apache.maven.surefire.Surefire.run(Surefire.java:177) 
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
        at 
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java: 
39) 
        at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImp l.java: 
25) 
        at java.lang.reflect.Method.invoke(Method.java:597) 
        at 
org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(Surefire Booter.java: 
345) 
        at 
org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java: 
1009) 
14-Nov-2011 14:42:20 org.bridj.AbstractBridJRuntime log 

Here is the Java class also :

@Library("QuicDispatchCpp")
class QuicLib {
	private static final Logger log = Logger.getLogger(QuicLib.class);

	// Must point to the directory where QuicDispatchCpp.dll lives.
	// Alternatively the system will search for the .dll on the path
	public static final String QUIC_LIB_PATH_PROP = "quic.library.path";

	private static QuicLib instance;
	
	static {
		final String quicLibPath = System.getProperty(QUIC_LIB_PATH_PROP);
		if(quicLibPath != null && !"".equals(quicLibPath)) {
			BridJ.addLibraryPath(quicLibPath);
		}else{
			log.warn("Property " + QuicLib.QUIC_LIB_PATH_PROP + " has NOT been set. \n" +
					"It's likely we won't find the required QuicDispatchCpp.dll, unless it's on the class path ! \n" +
					"If you see a UnsatisfiedLinkError, you'll know why ! :)");
		}
		
		BridJ.register();
	}

	native public static Pointer<IQuicDispatch> QuicCreateDispatch();
	native void QuicReleaseDispatch(Pointer<IQuicDispatch> piDispatch);

	native Pointer<IDispatchVariant> QuicCreateDispatchVariant();
	native void QuicReleaseDispatchVariant(Pointer<IDispatchVariant> piVariant);
	native void	QuicLiberateDispatchVariant(Pointer<IDispatchVariant> piVariant);

	/**
	 * Singleton factory method
	 * @return The only and staticly unique instance of the library.
	 */
	public static QuicLib instance(){
		if(instance == null){
			instance = new QuicLib();
		}

		return instance;
	}
}

I get the error when doing QuicLib.QuicCreateDispatch();

Thanks,
dan

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#11
