### ISSUE TITLE
[ScalaCL Plugin]: Missing dereference of ArrayOps$ofRef

### ISSUE THREAD

**Issue by frgomes** [ochafik/nativelibs4java#209]
I've found what seems to be a failure to call ArrayOps$ofRef.apply(), in the code generated by the compiler plugin.
If I turn off the compiler plugin, the code 'works' as expected, despite very slow.

A class cast exception happens like shown below because an ArrayOps$ofRef is passed, instead of the result of ArrayOps$ofRef.apply(), which should return an Array[Float].

    java.lang.ClassCastException: scala.collection.mutable.ArrayOps$ofRef cannot be cast to [Lscalacl.CLArray;
        at scalacltests.Test209.mean(Test209.scala:11)
        at scalacltests.Test209.testMean(Test209.scala:18)

Relevant piece of code:

    package scalacltests
    
    import scalacl._
    import org.junit.{Assert, Test, Ignore}
    
    class Test209 {
      private implicit val context = Context.best
      println(context)
    
      def $mean(av : Array[CLArray[Float]]) : Array[Float] = { av.map( v => { v.sum / v.length } ) }
      def mean(av : Array[Array[Float]]) : Array[Float]  = { $mean(av.map(v => { v.cl })) }  //-- line 11
    
      @Test
      def testMean() : Unit = {
        val a = Array[Float](1.2F, 1.5F, 1.6F, 1.8F)
        val b = Array[Float](2.2F, 2.5F, 2.6F, 2.8F)
        val m = Array(a,b)
        mean(m).foreach(f => println(f))  //-- line 18
      }
    }

Environment:

    scalacl-compiler-plugin 0.3-SNAPSHOT
    JDK1.6.0-29 amd64
    Scala 2.9.1
    Maven 3.0.3
    Debian 6.0.3
    GeForce GTX460

**Comment by ochafik** [comment]
Assumed stale. Please reopen if it's not.
