### ISSUE TITLE
Problems parsing 'boost' libraries 

### ISSUE THREAD

**Issue by eoh667** [ochafik/nativelibs4java#224]
Hi,

I am trying to generate a wrapper for a somewhat complex C++ library / interface that mostly relies on the c++ boost library. While many parts appear to convert quite well, there are two errors I get over and over again:

```
1. /opt/local/include/boost/config.hpp:7:23: error: Expected string or header, not <
2. /opt/local/include/boost/type_traits/type_with_alignment.hpp:24:46: error: macro BOOST_PP_CHECK_2 has 2 parameters but given 1 args
```

The actual files / position vary, but the "Expected string" / "parameters but given" come up regularly. Looking into the boost files lines which cause it are, for example: 

```
1: #  define BOOST_USER_CONFIG <boost/config/user.hpp>
2: #define BOOST_TT_ALIGNMENT_BASE_TYPES BOOST_PP_TUPLE_TO_LIST( \
        12, ( \
        char, short, int, long,  ::boost::long_long_type, float, double, long double \
        , void*, function_ptr, member_ptr, member_function_ptr))

```

Please let me know if you need anything else.

**Comment by ochafik** [comment]
This issue was moved to ochafik/JNAerator#23
