### ISSUE TITLE
ObjCppParser resolves CPP Methods as VariablesDeclaration 

### ISSUE THREAD

**Issue by zillazilla** [ochafik/nativelibs4java#235]
ObjCppParser resolves the following methods incorrectly as VariablesDeclaration Objects:

public short AClass::getX(void);
public long AClass::getX(void);
public AClass::AClass(void);

In contrast, these methods are correctly resolved as Function Objects:

public int AClass::getX(void);
public xxx AClass::getX(void);
public AClass::~AClass(void);

Moreover, these methods are not resolved at all (parser error):
public short AClass::getX(void)const;
public long AClass::getX(void)const;

Failed to match any alternative with token [@4,13:18='AClass',<13>,1:13]
	 File: null:1
	Input: public   short   AClass :: getX ( void )
	 Rule: 539:4: ({...}? => pragmaContent |{...}? => templateDef | functionDeclaration |{...}? => externDeclarations | varDecl ';' | objCClassDef | typeDef | forwardClassDecl | namespaceDecl )
	Stack: []

**Comment by ochafik** [comment]
This issue was moved to ochafik/JNAerator#25
