### ISSUE TITLE
Bridj 0.6 won't work on java 5

### ISSUE THREAD

**Issue by aaime** [ochafik/nativelibs4java#237]
While the library is compiled with Java 5 binary compatibility it won't work because it uses Java 6 only API.

So far I've noticed this one:

java.lang.NoSuchMethodError: java.util.Properties.stringPropertyNames()Ljava/util/Set;

but there might be others. In GeoTools 2.7.x series we also have to respect Java 5 compliance and have found that pretty much the only way to avoid these problems is to either use a JDK 1.5 locally to build the project or have continuous build that uses Java 1.5 to double check the project actually works there.

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#12
