### ISSUE TITLE
FileNotFoundException: org/bridj/lib/linux x64/atiocl64.so

### ISSUE THREAD

**Issue by chinasaur** [ochafik/nativelibs4java#241]
Possibly related to: https://github.com/ochafik/nativelibs4java/issues/206

But this is on a Debian box with an NVIDIA GPU.  JavaCL-1.0.0-RC1. Not sure why it's going for ATI stuff; probably has something to do with OpenCLProbeLibrary?  Runs fine on another box that is supposed to have identical setup...

**Comment by ochafik** [comment]
This issue was moved to ochafik/JavaCL#11
