### ISSUE TITLE
stuck on boost library

### ISSUE THREAD

**Issue by axet** [ochafik/nativelibs4java#245]
Hello!

I'm trying to run jnaerator on libtorrent and it's stuck forever generating sources. i gess that is a boost library problem.

any suggestions?

source is here:

* git clone -b feature-javabindings https://code.google.com/p/mircle.libtorrent/
* ./autotools.sh
* ./configure
* make
* cd bindings/java
* make

Python.Boost library http://www.boost.org/doc/libs/1_48_0/libs/python/doc/

**Comment by ochafik** [comment]
This issue was moved to ochafik/JNAerator#26
