### ISSUE TITLE
[BridJ] SEVERE: Failed to get address of method

### ISSUE THREAD

**Issue by finson** [ochafik/nativelibs4java#262]
Olivier:  Thank you for the Issue #261 fix.  I cleaned my local maven repo, pulled all the recent git changes into nl4j, regenerated the libraries (not including Scala related because Scalaxy build hangs with 100% CPU ...), and tried to run again.  I now get the following:

```
SEVERE: Failed to get address of method public static native org.bridj.Pointer org.bridj.dyncall.DyncallLibrary.dcNewStruct(long,int)
```

and the same error for 'dcCloseStruct, dcStructSize, dcSubStruct, dcStructField, dcStructAlignment, dcFreeStruct, and dcDefineStruct'.  Looking at DyncallLibrary.java, last updated Dec 31, 2011, those methods are there in their Java form.  However, they don't appear to be present in the bridj.dll that I have from the github repo which was last updated on Jan 02, 2012.  Is it possible that bridj.dll was generated from an out of date header?  Thanks.

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#13
