### ISSUE TITLE
JNAerator: JNA not working from Weblogic?

### ISSUE THREAD

**Issue by lagarcia** [ochafik/nativelibs4java#277]
Hi

Recently I was trying to use JNA/JNAerator in order to invoke methods from a C library within a Java 6 application. I was having some troubles doing the same thing using JNI because an error was raising from a method within the C native library when I executed the Java app. 

The thing is that with JNA I was able to skip the error that I was catching when using JNI, but when I included the functionality that was making use of the C native library via JNA within a web application deployed on Weblogic, it didn't seem to work correctly. The native method that seems to fail is loading a file from a file path that is passed as argument. The raising error suggests that the file is not loaded. When using the same function from the standalone app it was working fine, but not from within the web app deployed on Weblogic. The libraries seem to be loaded fine. I didn't try with other app servers.

Do you have any experience or feedback using JNA from web apps?

Thanks and regards,
Luis

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#14
