### ISSUE TITLE
Support for IndexedSeq

### ISSUE THREAD

**Issue by fdietze** [ochafik/nativelibs4java#286]
Hi there,

i'm working on a project where I use ArrayBuffers in performance-critical sections. In some places I was able to replace them with Arrays, so they got while-optimized by the scalacl-compiler-plugin. But in other cases it would make the code way more unreadable or easier to replace them with while-loops myself.

So I'd like to see support for optimization of IndexedSeq in the scalacl-compiler-plugin.

Thank you!
Felix

**Comment by ochafik** [comment]
This issue was moved to ochafik/Scalaxy#26
