### ISSUE TITLE
vtable not found 

### ISSUE THREAD

**Issue by alexrabo** [ochafik/nativelibs4java#287]
Upon running jnaerator with mydll and a header, I am getting following error 

"SEVERE: Failed to find a vtable for type mylib.ClassName"  I am using jnaerator-0.9.10.jar.  From command line I  entered
java -jar janerator-0.9.10.jar -arch win32 -library MyLib MyLib.h MyLib.dll.  The Class I am trying to instantiate is a pure virtual C++.  If it was C++, I would be creating a derived class and implementing all method calls.  I pretty sure this Class is inside MyLib.dll. Why can I not see vtable of functions for this class?

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#15

**Comment by belerweb** [comment]
any update?
