### ISSUE TITLE
Mac OS X 64 bit broken

### ISSUE THREAD

**Issue by slajar** [ochafik/nativelibs4java#294]
I have a universal darwin library that has 32 bit and 64 bit binaries encapsulated. Both work fine in my natve test envioronment. I managed to get the 32 bit running trough jnaerted code (bridj) with "java -d32". Unfortunetely, when I switch over to 64 bit by turning on the "-d64" switch it crashes with the first ".get()" call I do in my sample code.

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#17
