### ISSUE TITLE
Parameterized constructor of C++ is not accessed when used BridJ

### ISSUE THREAD

**Issue by friends4kunal** [ochafik/nativelibs4java#313]
Hi 
If my Native C++ Code contains class

Class A
{
  public :
   A( int i, float b, char c)
    {   // Constructor } 
};

When try to create object of this class A in Java code through BridJ , nothing works, says not able to access default constructor.  When used constructor with no parameter everything works perfect. Also when I used BridJ through Plug ins it does not work for CALLBACK , but when I use normal java app and access through main () CALLBACK works perfect

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#20
