### ISSUE TITLE
VTable Alignment Issue

### ISSUE THREAD

**Issue by asherkin** [ochafik/nativelibs4java#318]
BridJ appears to automatically handle the "extra" virtual dtor that GCC adds into the vtable (which in most cases would give you seamless comparability).

However, in the case of abstract classes, this is not present, causing the function indices to be miss-aligned when calling.

While I haven't tested (and therefore really shouldn't mention it, but, shhh :P), I'm guessing this'll also be a problem with how MSVC and GCC order overloaded functions (and even weirder, overloads from inherited classes) differently as well.

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#21
