### ISSUE TITLE
JavaCL scrambles values on BIG ENDIAN (ATI) device

### ISSUE THREAD

**Issue by gidili** [ochafik/nativelibs4java#322]
In relation to this thread on google groups: 

https://groups.google.com/forum/?fromgroups#!topic/nativelibs4java/lLM5VNeiEGo

Even with appropriate byte ordering instructions [ https://gist.github.com/3011101/ ], values are misinterpreted by the device.

The device I am testing on is an ATI Radeon HD4850.

**Comment by ochafik** [comment]
This issue was moved to ochafik/JavaCL#12
