### ISSUE TITLE
Javadoc problems

### ISSUE THREAD

**Issue by kazocsaba** [ochafik/nativelibs4java#323]
Some issues with the Javadoc that I stumbled upon without looking explicitly.

Pointer.validElements(): mentions "valid bytes" at one place.
Pointer.getFloatBuffer() and Pointer.getFloatBuffer(long length): mention byte offset
CLContext.createFloatBuffer(Usage kind, Pointer<Float> data): talk about the copy parameter that this overload doesn't have

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#22
