### ISSUE TITLE
Many unknown types

### ISSUE THREAD

**Issue by Xabster** [ochafik/nativelibs4java#331]
First I'd like to say that I'm not sure this is a bug.

I'm using this bat file: http://pastebin.com/XS9DF1qV

To generate some stuff from this header file: http://pastebin.com/8YtRPfJ4

And I'm getting unknown types for the following types: UCHAR, COLORREF, time_t, HWND, LPCSTR, LPVOID, LPSTR, REFIID

They're created as empty public static interfaces like this: public static interface LPSTR { };

**Comment by ochafik** [comment]
This issue was moved to ochafik/JNAerator#34
