### ISSUE TITLE
Bridj - JAWTUtils.withLockedSurface slows down

### ISSUE THREAD

**Issue by sampsonk** [ochafik/nativelibs4java#332]
I'm trying to run JAWTUtils.withLockedSurface() in a loop to perform rendering.  However, even if no rendering is performed, the loop slows down dramatically within the first few seconds until it eventually settles into a specific range.

I'm using Bridj to interface with DirectX 11.  When I try to do the above while rendering a single triangle each frame, the JVM eventually crashes (seems to happen after rendering about 10,000 times).

I've included code below to repro the issue along with output.  Running on Windows 7 64-bit, Bridj 0.6.1 and 0.6.2-snapshot-20120722, jdk 1.6.0_21

```java
import java.awt.Component;

import javax.swing.JFrame;

import org.bridj.jawt.JAWT;
import org.bridj.jawt.JAWTUtils;
import org.bridj.jawt.JAWTUtils.LockedComponentRunnable;
import org.bridj.jawt.JawtLibrary.JNIEnv;

public class LockedSurfaceTest {
	public static void main(String[] args) {
		JFrame frame = new JFrame("withLockedSurface test");
		frame.setSize(800, 600);
		frame.setIgnoreRepaint(true);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setVisible(true);
		
		JNIEnv env = JAWTUtils.getJNIEnv();
		JAWT jawt = JAWTUtils.getJAWT(env);
		LockedComponentRunnable lcr = new LockedComponentRunnable() {
			@Override
			public void run(Component comp, long peer) {
			}
		};
		int j = 0;
		long startTime = System.currentTimeMillis();
		while(frame.isEnabled()) {

			if(frame.isVisible())
				JAWTUtils.withLockedSurface(env, jawt, frame, lcr);
		
			j++;
			long endTime = System.currentTimeMillis();
			if(endTime - startTime >= 1000) {
				System.out.println("frames = " + j);
				j = 0;
				startTime = endTime;
			}
		}
	}
}
```

Output:

frames = 1952
frames = 867
frames = 637
frames = 566
frames = 474
frames = 431
frames = 380
frames = 373
frames = 354
frames = 339
frames = 305
frames = 309
frames = 270
frames = 280
frames = 268
frames = 260
frames = 253
frames = 234
frames = 230
frames = 230
frames = 215
...

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#23
