### ISSUE TITLE
JavaCL.createBestContext() hangs on GTX680 (Kepler architecture)

### ISSUE THREAD

**Issue by karolovbrat** [ochafik/nativelibs4java#343]
Hi Olivier,

when I try to run my JavaCL application it hangs in JavaCL.createBestContext().

Used HW and SW is

CentOS linux
GTX 680 (Kepler architecture) with Cuda Toolkit 4.2

When I try to run it under same settings on GTX 480 (Fermi architecture) it runs just fine.

Thank you very much for investigating the matter.
Regards,
Jan

**Comment by ochafik** [comment]
This issue was moved to ochafik/JavaCL#15
