### ISSUE TITLE
vector<unsigned char > error

### ISSUE THREAD

**Issue by miho** [ochafik/nativelibs4java#344]
Hi,

when trying to create wrappers for [rtmidi](http://www.music.mcgill.ca/~gary/rtmidi/) library I get the following error:

    1. ERROR in file:///rtmidi/RtMidiLibrary.java (at line 45)
    public static interface vector<unsigned char > {
	                                        ^^^^

I used the following command:

    java -jar jnaerator-0.11-SNAPSHOT-20121008.jar -I. -library RtMidi RtMidi.h librtmidi.dylib -mode StandaloneJar

My system: `Mac OS X 10.8, Java 1.7.0_07`

Regards,

Michael Hoffer

**Comment by ochafik** [comment]
This issue was moved to ochafik/JNAerator#36
