### ISSUE TITLE
Better usability for parallel random

### ISSUE THREAD

**Issue by kozlov-p-v** [ochafik/nativelibs4java#347]
Now, the ParallelRandom class http://nativelibs4java.sourceforge.net/javacl/api/stable/com/nativelibs4java/opencl/util/ParallelRandom.html have only few methods. And all of them can only return pointers of Integer which distrubute on [-Integer.MAX_VALUE,Integer.MAX_VALUE] 
It is not really comfortable to work with it.

It will be very useful to have methods which create vectors, uniformly distributed on [0,1) or oven on [left,right] - something like createRandomDoubles(int size, double left, double right).

It is just a syntactic sugar for exising operations.

**Comment by ochafik** [comment]
This issue was moved to ochafik/JavaCL#16
