### ISSUE TITLE
JNAerator self-extraction does not work

### ISSUE THREAD

**Issue by leahxschmidt** [ochafik/nativelibs4java#351]
To reproduce, do the following (instructions assume you are using Linux, but I've also gotten the same result on win32 with the appropriate changes):
 git clone https://github.com/leahxschmidt/testjnaerator.git
cd testjnaerator
make
cd java
javac -cp test_linux.jar:. JavaTest.java
java -cp test_linux.jar:. -Djna.nosys=true JavaTest 

I would expect this to run correctly, but it does not.

If I first extract the jar and manually configure the library path, it does run:
jar xf test_linux.jar
java -cp test_linux.jar:. -Djna.nosys=true -Djna.library.path=lib/linux_x64/  JavaTest

Naturally, I don't want to have to do that.  I don't have this problem if I use 0.9.7, but I do with 0.10.0.

**Comment by ochafik** [comment]
This issue was moved to ochafik/JNAerator#38
