### ISSUE TITLE
Please add -scanSymbols support for .tlb and .exe files

### ISSUE THREAD

**Issue by bernard01** [ochafik/nativelibs4java#353]
Hi,

Hopefully some java source code can be generated from type libraries. These can be extracted from .tlb files, .dll files, .exe files and possibly others.

I used jacoZoom to generate from SketchUp.exe. http://www.sketchup.com has a free version. This was only partially successful because jacoZoom and others do not support UDT arrays in parameters. But there may be other .exe files that are easier to generate from.

DesignCad 3dMax http://www.imsidesign.com/Products/DesignCADSeries/DesignCAD3DMAXV22/tabid/1832/Default.aspx has a trial download. It contains Dcad22.tlb in its root program directory. jacoZoom generates good java files from it.

It would be really nice if jnaerator could be the reference starting point for interfacing with ANY native library because it seems that support for other java native open source projects and even some commercial products is no longer available.

Thanks.

**Comment by ochafik** [comment]
This issue was moved to ochafik/JNAerator#40
