### ISSUE TITLE
BridJ 0.6.3 release to Maven Central

### ISSUE THREAD

**Issue by sarxos** [ochafik/nativelibs4java#381]
Hi Olivier,

Just wanted to ask you if you have already some target dates in your plans regarding 0.6.3 release?

I'm asking because I'm planning to release my project soon and I'm not sure if I can commit any changes that requires 0.6.3 to be deployed along with my JAR.

**Comment by ochafik** [comment]
0.7.0 was released last week (still struggling to find the time to send release notes :-S), sorry for the *extreme* delay. Projects are not split from nativelibs4java, to ease up contributions.

**Comment by sarxos** [comment]
Great! Thanks @ochafik!
