### ISSUE TITLE
Memory consumption by Pointer allocations.

### ISSUE THREAD

**Issue by haron4igg** [ochafik/nativelibs4java#404]
Hi Olivier,

I'm working with continuos calculations, which producing a lot of double arrays from C library. Using BridJ caused to real memory consumption problem.

By VisualVM tool i figured out that all allocated and released pointers are still exist in memory and being garbaged only after manual invocation of GC.

Here it is my code, may be i did something wrong..:

NativeCalculatorLibrary.OutputCallback callback = new NativeCalculatorLibrary.OutputCallback() {
            @Override
            public void apply(double v, Pointer<Double> doubles, double v2) {
                if (doubles != null && listener != null) {
                    double [] input = doubles.getDoubles(dimension);
                    listener.onReceivePoints(v, input, v2);
                    doubles.release();
                }
            }
        };

I had a similar problem with JNI, but it was fixed by deleting local environment reference after performing callback.

Thank you in advance,
Igor.

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#27
