### ISSUE TITLE
SIGSEGV on Ubuntu using JavaCL

### ISSUE THREAD

**Issue by tarelli** [ochafik/nativelibs4java#405]
This happens either using CPU or GPU device:

    #
    # A fatal error has been detected by the Java Runtime Environment:
    #
    #  SIGSEGV (0xb) at pc=0x0000000000000000, pid=27283, tid=140378190874368
    #
    # JRE version: 7.0_17-b02
    # Java VM: Java HotSpot(TM) 64-Bit Server VM (23.7-b01 mixed mode linux-amd64     compressed oops)
    # Problematic frame:
    # C  0x0000000000000000
    #
    # Failed to write core dump. Core dumps have been disabled. To enable core dumping,     try "ulimit -c unlimited" before starting Java again
    #
    # An error report file with more information is saved as:
    # /home/mike/geppetto/serviceability/error.log
    #
    # If you would like to submit a bug report, please visit:
    #   http://bugreport.sun.com/bugreport/crash.jsp
    # The crash happened outside the Java Virtual Machine in native code.
    # See problematic frame for where to report the bug.

With stacktrace:

    Stack: [0x00007fac58238000,0x00007fac58339000],  sp=0x00007fac58337098,  free     space=1020k
    Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
    j  com.nativelibs4java.opencl.library.OpenCLLibrary.clReleaseDevice(J)I+0
    j  com.nativelibs4java.opencl.CLDevice.clear()V+7
    j  com.nativelibs4java.opencl.CLAbstractEntity.doRelease()V+10
    j  com.nativelibs4java.opencl.CLAbstractEntity.finalize()V+1
    v  ~StubRoutines::call_stub
    J  java.lang.ref.Finalizer.invokeFinalizeMethod(Ljava/lang/Object;)V
    J  java.lang.ref.Finalizer.access$100(Ljava/lang/ref/Finalizer;)V
    J  java.lang.ref.Finalizer$FinalizerThread.run()V
    v  ~StubRoutines::call_stub

The full specs of the system are:

*Java:* 
java version "1.7.0_15" 
Java(TM) SE Runtime Environment (build 1.7.0_15-b03) 
Java HotSpot(TM) 64-Bit Server VM (build 23.7-b01, mixed mode) 

*Distro:* 
Ubuntu 12.04.2 LTS 

*Kernel:* 
Linux mike-pdn 3.2.0-40-generic #64-Ubuntu SMP Mon Mar 25 21:22:10 UTC 2013 
x86_64 x86_64 x86_64 GNU/Linux 

*CPU:* 
Intel(R) Core(TM)2 Quad CPU Q8300 @ 2.50GHz 

*GPU:* 
NVIDIA Corporation GT218 [GeForce 310] (rev a2) 

Full logs:
http://pastebin.com/h2tcbsX7
http://pastebin.com/UiiCDquj

**Comment by ochafik** [comment]
This issue was moved to ochafik/JavaCL#17
