### ISSUE TITLE
Process of edge case struct usage

### ISSUE THREAD

**Issue by rit001** [ochafik/nativelibs4java#415]
The following does not correctly define VixDiskLibConnectParam

    struct VixDiskLibConnectParam;
    typedef struct VixDiskLibConnectParam *VixDiskLibConnection;
    VixDiskLib_Disconnect(VixDiskLibConnection connection);

This does seem to create the correct code

   struct VixDiskLibConnectParam {};
   typedef struct VixDiskLibConnectParam *VixDiskLibConnection;
   VixDiskLib_Disconnect(VixDiskLibConnection connection);

As I understand C something like 'struct VixDiskLibConnectParam' allows the compiler to create a place holder so that the struct's name can be used in a header without having to completly define it or #include it from elsewhere.

**Comment by ochafik** [comment]
This issue was moved to ochafik/JNAerator#47
