### ISSUE TITLE
Pointer to enums seems to be broken

### ISSUE THREAD

**Issue by MichaelEllis** [ochafik/nativelibs4java#416]
=== C Header =========

    typedef enum
    {
        None         = 0,
        Apple        = 1,
        Pear         = 2,
        Orange       = 4,
        Banana       = 8
    } Fruit;

    void getFruit(Fruit* fruit);
===============

=== JAVA TEST ===
	@Test
	public final void testThing() {
		IntValuedEnum<Fruit> fruit = Fruit.Apple;
		Pointer<IntValuedEnum<Fruit>> pFruit = Pointer.pointerTo(fruit);
		pFruit.set(Fruit.Banana);
		
		System.out.printf("fruit=%s\n", fruit);
		System.out.printf("pFruit=%s pFruit.get()=%s\n", pFruit, pFruit.get());
		Assert.assertEquals(fruit, Fruit.Banana); // FAILS
	
	}

===============

The assert fails and the output is

fruit=Apple
pFruit=Pointer(peer = 0x100552fc0, targetType = org.bridj.IntValuedEnum, order = LITTLE_ENDIAN) pFruit.get()=Fruit(8 = None | Banana)

I am using the 	JNAerator 0.12-SNAPSHOT 20130609 from 
http://code.google.com/p/jnaerator/downloads/detail?name=jnaerator-0.12-SNAPSHOT-20130609.jar

Trying the latest build from the GIT repository seems to be broken completely.

**Comment by ochafik** [comment]
Closing since unlikely to fix / change. Thanks again for your suggestions!
