### ISSUE TITLE
JVM crash on GC with current maven snapshot

### ISSUE THREAD

**Issue by twitwi** [ochafik/nativelibs4java#420]
Hi @ochafik 

I have a (now) very simple program that crashes with the latest maven snapshots but works with javacl-1.0.0-RC3.jar.

    public static void main(String[] args) {
        CLContext context = JavaCL.createBestContext();
        CLDevice[] devices = context.getDevices();
        for (int i = 0; i < devices.length; i++) {
            System.err.println(i+": "+devices[i]);
        }
        System.err.println("Now GC'ing");
        System.gc(); // crash here
        System.err.println("GC'ed");
    }

I run using optirun under linux mint 15, 64bits, with a "NVS 5400M (NVIDIA CUDA)" device. The rest of the program works fine (complicated opencl kernel work) but the GC crashes the VM with:

    0: NVS 5400M (NVIDIA CUDA)
    Now GC'ing
    #
    # A fatal error has been detected by the Java Runtime Environment:
    #
    #  SIGSEGV (0xb) at pc=0x00007f8e46073bcc, pid=15591, tid=140248881133312
    #
    # JRE version: 7.0_21-b02
    # Java VM: OpenJDK 64-Bit Server VM (23.7-b01 mixed mode linux-amd64 compressed oops)
    # Problematic frame:
    # V  [libjvm.so+0x75cbcc]  PSRootsClosure<false>::do_oop(oopDesc**)+0xc

It might be a temporary issue (or specific to my device) but I prefer to report it.

Rémi

**Comment by ochafik** [comment]
This issue was moved to ochafik/JavaCL#18
