### ISSUE TITLE
LastError not thrown

### ISSUE THREAD

**Issue by skyewire** [ochafik/nativelibs4java#426]
LastError is often not thrown when it should be. Here is a small sample program that demonstrates the problem:

```java
import org.bridj.*;
import org.bridj.ann.*;
import org.bridj.ann.Runtime;

public class LastErrorTest
{
	public static void main(String[] args) throws Exception
	{
		System.out.println("Registering AdvApi32");
		BridJ.register(Advapi32.class);
		
		System.out.println("Calling OpenServiceW with bad parameters 1");
		Advapi32.OpenServiceW(null, null, 0);
		System.out.println("Should have thrown LastError, but did not!");
		
		System.out.println("Calling OpenServiceW with bad parameters 2");
		Advapi32.OpenServiceW(null, null, 0);
		System.out.println("Should have thrown LastError, but did not!");
	}

	@Library("advapi32")
	@Runtime(CRuntime.class)
	private static class Advapi32
	{
		native public static Pointer<Character> OpenServiceW(
			Pointer<Character> hSCManager,
			Pointer<Character> lpServiceName,
			int dwDesiredAccess) throws LastError;
	}
}
```

I'm testing on Windows 7 64-bit. With the 64-bit JVM, LastError is thrown for the 2nd function call only. With the 32-bit JVM, LastError is never thrown. Sample output for both 64-bit and 32-bit JVMs:

```
C:\Test>"C:\Program Files\Java\jre7\bin\java.exe" -classpath .;bridj-0.6.2-windows-only.jar LastErrorTest
Registering AdvApi32
Calling OpenServiceW with bad parameters 1
Should have thrown LastError, but did not!
Calling OpenServiceW with bad parameters 2
Exception in thread "main" org.bridj.LastError: The handle is invalid. (error code = 6)
        at org.bridj.LastError.throwNewInstance(LastError.java:53)
        at LastErrorTest$Advapi32.OpenServiceW(Native Method)
        at LastErrorTest.main(LastErrorTest.java:17)

C:\Test>"C:\Program Files (x86)\Java\jre7\bin\java.exe" -classpath .;bridj-0.6.2-windows-only.jar LastErrorTest
Registering AdvApi32
Calling OpenServiceW with bad parameters 1
Should have thrown LastError, but did not!
Calling OpenServiceW with bad parameters 2
Should have thrown LastError, but did not!
```

The root cause of this problem is that GetLastError() is only called in Exceptions.c throwIfLastError() and this happens way too late after the actual native function call. The BridJ native code may call other Windows functions between the actual native function call and throwIfLastError(), so by the time GetLastError() is called, it is returning the error code for these other Windows functions, which will typically be 0 (succeeded). To fix, GetLastError() needs to be called immediately after the actual native function call. You don't have to deal with the error code at this stage (you can store it in a thread-local and deal with it later) but you have to store it immediately.

The same problem probably exists for errno, although I haven't tested this.

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#28
