### ISSUE TITLE
Allow getting last error without using the LastError exception

### ISSUE THREAD

**Issue by skyewire** [ochafik/nativelibs4java#427]
BridJ needs an API to get the last error (i.e. errno or Windows GetLastError()) without declaring that the native function throws LastError.

The reason for this is that some Windows API functions succeed, but still set the last error. A typical example is CreateMutex: if the mutex already exists, the function succeeds and returns a handle to the mutex (which must be closed) and sets the last error to ERROR_ALREADY_EXISTS. It's not possible to use this function correctly with BridJ at the moment:

- If your native function throws LastError, then you'll never receive the mutex handle in the ERROR_ALREADY_EXISTS case. This causes a handle leak.
- If your native function does not throw LastError, then you won't know whether the mutex already existed or not. In some cases, this is vital information.

The last error should be stored in a thread-local variable and be available for the Java code to query until the next native function is called from that thread.

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#29
