### ISSUE TITLE
Nested enum definitions not translated properly to method signatures

### ISSUE THREAD

**Issue by ilganeli** [ochafik/nativelibs4java#447]
If I have a structure:
typedef struct _PttPriority
{
    enum Enum
    {
        Low, Normal, High
    };
} PttPriority;

This definition is useful since it enables the following syntax: PttPriority::Low and this enum can be used like "PttPriority::Enum enumType;"

The Jnaerator succesfully translates this definition into:

public class PttPriority extends StructObject {
	/**
	 * enum values<br>
	 * <i>native declaration : PttStructs.h:41</i>
	 */
	public enum Enum implements IntValuedEnum<Enum > {
		Low(0),
		Normal(1),
		High(2);
      }
}

However, if I have - 
class Foo{
public:
      Foo(PttPriority::Enum enum);
}

The Jnaerator fails to translate that into an appropriately parameterized Java constructor. The class ends up being defined as an abstract class that looks like:
public abstract class Foo extends CPPObject {
      public Foo(Enum enum){
      }
}

and it reports a Conversion Error:
	/** Conversion Error : PttPriority::Enum (failed to convert type to Java (undefined type)) */

**Comment by ochafik** [comment]
This issue was moved to ochafik/JNAerator#51
