### ISSUE TITLE
Source build breaks on pthread4java

### ISSUE THREAD

**Issue by ilganeli** [ochafik/nativelibs4java#448]
I am attempting to rebuild to get a bug fix for a pointer issue and have failed when building PThread4Java. 

[INFO] Reactor Summary:
[INFO]
[INFO] NativeLibs4Java Common Configuration .............. SUCCESS [3.514s]
[INFO] Interop Integration Root .......................... SUCCESS [0.034s]
[INFO] Maven Velocity Code Generator ..................... SUCCESS [9.307s]
[INFO] BridJ (NativeLibs4Java C/C++ Interop Layer) ....... SUCCESS [26.846s]
[INFO] Anarres JCPP (with JNAerator modifications) ....... SUCCESS [4.900s]
[INFO] JNAerator Parent Project .......................... SUCCESS [0.033s]
[INFO] OChafik's General Utilities ....................... SUCCESS [6.322s]
[INFO] OChafik's Swing Utilities ......................... SUCCESS [7.949s]
[INFO] JNAerator Runtime ................................. SUCCESS [6.174s]
[INFO] JNAerator Rococoa Runtime ......................... SUCCESS [3.108s]
[INFO] JNAerator Parser .................................. SUCCESS [19.223s]
[INFO] JNAerator CLI and Studio Tools .................... SUCCESS [12.317s]
[INFO] JNAerator Maven Plugin ............................ SUCCESS [4.326s]
[INFO] JavaCL Parent Project ............................. SUCCESS [0.043s]
[INFO] LibCL ............................................. SUCCESS [0.371s]
[INFO] OpenCL4Java / BridJ ............................... SUCCESS [3.728s]
[INFO] NativeLibs4Java Common Utilities .................. SUCCESS [3.275s]
[INFO] JavaCL Core / BridJ ............................... SUCCESS [8.865s]
[INFO] JavaCL Generator / BridJ .......................... SUCCESS [3.287s]
[INFO] Maven JavaCL Plugin ............................... SUCCESS [3.194s]
[INFO] JavaCL / BridJ .................................... SUCCESS [6.889s]
[INFO] JavaCL Demos / BridJ .............................. SUCCESS [4.904s]
[INFO] JavaCL Interactive Image Demo / BridJ ............. SUCCESS [4.190s]
[INFO] JavaCL BLAS / BridJ ............................... SUCCESS [11.051s]
[INFO] JavaCL OpenGL Demos / BridJ ....................... SUCCESS [7.863s]
[INFO] JavaCL Tutorial ................................... SUCCESS [4:08.969s]
[INFO] JavaCL Simple Tutorial Archetype .................. SUCCESS [0.312s]
[INFO] JavaCL Tutorials Root / BridJ ..................... SUCCESS [0.034s]
[INFO] PThread4Java ...................................... FAILURE [0.114s]
[INFO] Idle Time Utility Library (BridJ-based & cross-platform)  SKIPPED
[INFO] JarShrinker ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6:53.279s
[INFO] Finished at: Tue Sep 24 17:41:53 EDT 2013
[INFO] Final Memory: 35M/115M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.nativelibs4java:maven-jnaerator-plugin:0.12-SNAPSHOT:generate (default) on project pthread4java:
 The parameters 'generateScala' for goal com.nativelibs4java:maven-jnaerator-plugin:0.12-SNAPSHOT:generate are missing or invalid -
> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginParameterException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pthread4java

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#32
