### ISSUE TITLE
See Java HotSpot warning using jnaerator during build

### ISSUE THREAD

**Issue by mwick** [ochafik/nativelibs4java#451]
See the following warning using jnaerator from ANT during a build:

Java HotSpot(TM) Server VM warning: You have loaded library /tmp/bridj.so7558773552115411714.so which might have disabled stack guard. The VM will try to fix the stack guard now.

Using jnaerator 10 on RedHat build server 2.6.18.

**Comment by ochafik** [comment]
This issue was moved to ochafik/JNAerator#52
