### ISSUE TITLE
invalid memory access and then seg fault on iMac with Radeon HD 4850

### ISSUE THREAD

**Issue by hakuliu** [ochafik/nativelibs4java#458]
I was having trouble getting anything to run on this particular hardware, and try to distill is to some reproducible cases...

I made a little test suite that can be accessed in the following link:
https://drive.google.com/file/d/0Byprex-Adx53c1V0UWN0a09ZdU0/edit?usp=sharing

the package includes a simple test in c which gets all platform and devices and displays some information of those devices.  It then runs a very simple kernel which takes a float * input and adds 1 to each element to produce the output.  This simple test case, of course, ran just fine on the machine in question.

There is another test in the package which performs the same basic test, but using the JavaCL RC3 package.  running this with ant gives me a segmentation fault.  (only sometimes...I think the first run is okay and second is bad....which is interesting)

I have included the output of both runs 
https://gist.github.com/hakuliu/7452553

I know the native code ran from JavaCL is probably not the same as the one as I have in my C code.  I'll have to possibly look through the native code called from JavaCL...  I'll continue investigating this error later as I know it's hard to get hardware of specific configuration...

**Comment by ochafik** [comment]
This issue was moved to ochafik/JavaCL#20
