### ISSUE TITLE
How can I translate an LPVOID parameter in JAVA

### ISSUE THREAD

**Issue by vhugo006** [ochafik/nativelibs4java#462]
When generating source code from JNAErator several callback methods not compile because the input parameters are LPVOID. Thus, when using Pointer.getPeer () method, which receives org.bridj.Pointer <T> as parameter, the code throws compilation errors.

How can I represent this variable in this context?

```
		/**
		 * Data analysis via the callback.<br>
		 * Original signature : <code>BOOL CLIENT_ParseDataByCallback(LPVOID, DWORD, fAnalyzerData, LDWORD)</code><br>
		 */
		public static int CLIENT_ParseDataByCallback(DhConfigSdkLibrary.LPVOID lpInBuffer, int dwInBufferSize, DhConfigSdkLibrary.fAnalyzerData cbAnalyzer, DhConfigSdkLibrary.LDWORD dwUser) {
			return CLIENT_ParseDataByCallback(Pointer.getPeer(lpInBuffer), dwInBufferSize, Pointer.getPeer(cbAnalyzer), Pointer.getPeer(dwUser));
		}
```

**Comment by ochafik** [comment]
Sorry I didn't reply earlier (missed second question), the issue here is parsing of CALLBACK, which JNAerator doesn't know about. Define it to an empty string `-DCALLBACK=` and JNAerator parses the callback just fine.

Please ask further non-bug questions on the mailing list :-)

Cheers
