### ISSUE TITLE
no suitable method found for getPeer(__gnuc_va_list)

### ISSUE THREAD

**Issue by asm0dey** [ochafik/nativelibs4java#465]
Hello!

I'm using jnaerator-0.12-SNAPSHOT, and bridj 0.7-SNAPSHOT, trying to jnaerate lame.h and getting such error while compiling 
```error: no suitable method found for getPeer(__gnuc_va_list)```

I'm using such command to generate project
```java -jar ~/jnaerator/jnaerator-0.12-SNAPSHOT-20130727.jar -f -runtime BridJ -I /usr/include/lame -I /usr/include/linux -mode AutoGeneratedMaven -I /usr/include/x86_64-linux-gnu/c++/4.8 -I /usr/include/x86_64-linux-gnu /usr/include/lame/lame.h```

PS:
Source header and resulting java are here: https://gist.github.com/asm0dey/50b0c679cd5d0a98e8fe

**Comment by ochafik** [comment]
This issue was moved to ochafik/JNAerator#54
