### ISSUE TITLE
JNAerator: Function missing with certain order of header files

### ISSUE THREAD

**Issue by hastebrot** [ochafik/nativelibs4java#470]
Hi!

I use the LLVM 3.3 C headers (http://llvm.org/releases/3.3/llvm-3.3.src.tar.gz) with JNAerator 0.11 (or 0.12-SNAPSHOT-20130727) under Windows 7 and Java 8.0-EA.

After I generate the java file, the function `LLVMCreateExecutionEngineForModule` from `$(LLVM_HOME)/include/llvm-c/ExecutionEngine.h` is missing in `src/main/java/org/llvm/binding/LLVMLibrary.java`.

Here is my `llvm.jnaerator`:

```
-library LLVM
-limitComments
-mode Directory
-package org.llvm.binding
-o $(DIR)/src/main/java
-I$(LLVM_HOME)/include/llvm-c/

$(LLVM_HOME)/include/llvm-c/Core.h
$(LLVM_HOME)/include/llvm-c/Disassembler.h
$(LLVM_HOME)/include/llvm-c/ExecutionEngine.h
```

If I change the order of the header files, the java file will contain `LLVMCreateExecutionEngineForModule`. Here are some permutations:

Function missing: Core.h, Disassembler.h, ExecutionEngine.h.
Function existent: Core.h, ExecutionEngine.h
Function existent: Core.h, ExecutionEngine.h, Disassembler.h

**Comment by ochafik** [comment]
This issue was moved to ochafik/JNAerator#56
