### ISSUE TITLE
Android JNI warning with Bridj 0.7

### ISSUE THREAD

**Issue by kesslerd** [ochafik/nativelibs4java#474]
Hi ochafik

I'm developing an application for android and use BridJ for native calls.

In Bridj 0.7 I get a JNI warning and the app crashes.

 JNI WARNING: instance jfieldID 0x0 not valid for class Lorg/bridj/MethodCallInfo; (GetBooleanField) in Lorg/bridj/JNI;.bindJavaMethodsToCFunctions:([Lorg/bridj/MethodCallInfo;)J (GetBooleanField)

kind regards
kesslerd

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#34
