### ISSUE TITLE
jnaerator seems to require specific glibc version

### ISSUE THREAD

**Issue by mineralwasser** [ochafik/nativelibs4java#484]
This is the output of the most recent jnaerator snapshot, 0.11 works:

     [java] Caused by: java.lang.UnsatisfiedLinkError: /tmp/BridJExtractedLibraries2732055613940647667/libbridj.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/BridJExtractedLibraries2732055613940647667/libbridj.so)
     [java]
     [java]     at java.lang.ClassLoader$NativeLibrary.load(Native Method)
     [java]     at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
     [java]     at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
     [java]     at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
     [java]     at java.lang.Runtime.load0(Runtime.java:795)
     [java]     at java.lang.System.load(System.java:1062)
     [java]     at org.bridj.Platform.initLibrary(Platform.java:419)
     [java]     ... 5 more
     [java] Exception in thread "main" java.lang.UnsatisfiedLinkError: org.bridj.Platform.sizeOf_ptrdiff_t()I
     [java]     at org.bridj.Platform.sizeOf_ptrdiff_t(Native Method)
     [java]     at org.bridj.Platform.<clinit>(Platform.java:231)
     [java]     at com.ochafik.lang.jnaerator.NativePlatform.getCurrentPlatform(NativePlatform.java:49)
     [java]     at com.ochafik.lang.jnaerator.JNAerator$1.<init>(JNAerator.java:226)
     [java]     at com.ochafik.lang.jnaerator.JNAerator.main(JNAerator.java:224)
     [java]     at com.ochafik.lang.jnaerator.JNAerator.main(JNAerator.java:197)

**Comment by ochafik** [comment]
This issue was moved to ochafik/JNAerator#60
