### ISSUE TITLE
JNAerator generates uncompilable Java for GnuTLS header for BridJ runtime

### ISSUE THREAD

**Issue by rdicroce** [ochafik/nativelibs4java#487]
I attempted to run the GnuTLS header through JNAerator using the BridJ runtime instead of JNA after I had the problems described in #485. The command I used was the same except for -runtime.

The generated GnutlsLibrary.java file contains these non-existent imports:
import gnutls_params_st.gnutls_dh_params_t;
import gnutls_params_st.gnutls_rsa_params_t;
import gnutls_retr2_st.gnutls_openpgp_privkey_t;
import gnutls_retr2_st.gnutls_x509_crt_t;
import gnutls_retr2_st.gnutls_x509_privkey_t;

Some of the other generated files have similar errors.

**Comment by ochafik** [comment]
This issue was moved to ochafik/JNAerator#62
