### ISSUE TITLE
[JavaCL] System's locale affects source code.

### ISSUE THREAD

**Issue by mcopik** [ochafik/nativelibs4java#489]
The locale settings in Linux systems have an impact on kernel source, which is definitely a bug. When the ```LC_NUMERIC``` is set to a language in which the integral and fractional parts are separated with a comma rather than with a dot (e.g. ```pl_PL.UTF-8```), then the fractional parts of floating-point literals are missing. For example:
```c
//selection is a floating−point value in interval [0 ,1)
if( selection < 0.5) {
    //never selected !
}
else if ( selection < 1.0) {
    //always selected!
}
```
This issue doesn't happen when the kernel is executed from a program written in C/C++, using standard OpenCL libraries.
I'm using JavaCL in version 1.0.0-RC3.

**Comment by ochafik** [comment]
This issue was moved to ochafik/JavaCL#22
