### ISSUE TITLE
Lack of understanding and strange observation on @Convention

### ISSUE THREAD

**Issue by ErwinBellon** [ochafik/nativelibs4java#494]
Please point me to a bit more explanation on @Runtime and @Convention. I can usually get it to work but do not understand how :-(

When declaring a COM interface, I include a @IID annotation but no further convention or runtime annotation. For a COM object I only provide @IID and @CLSID. I would assume, however, that at least some indication of calling convention were requested. And in some DirectX declarations I detected that both COMRuntime and StdCall were provided.

When declaring Windows API functions resident in a dll, I usually get the stuff working by including @Runtime(CPPRuntime.class). But if I also include @Convention(StdCall) in the assumption that this refers to the ‘WINAPI’ calling convention, things go wrong.

But for the GetKeyState function in User32.dll I did have to include @Convention(StdCall) or the  application would crash (at least in a 32 bit JVM; it seemed to work in a 64 bit environment).

Thus, whereas for GetKeyState I HAD TO include the calling convention, I WAS NOT ALLOWED TO do so for a function like RegQueryInfoKeyW in AdvApi32.dll. The former function returns a 16 bit value instead one with 32 bits, but I would assume that this is unrelated.

Many thanks,

Erwin

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#36
