### ISSUE TITLE
Getting Linux JVM stack guard disabled issue

### ISSUE THREAD

**Issue by Urge2Learn** [ochafik/nativelibs4java#510]
Getting Linux JVM stack guard disabled issue. Referred #468, and tried all the approaches, still no improvement. Using 0.7-SNAPSHOT. Even if the generated .so is of 64 bit version from a native code that has a deprecated method. Changing the native code to replace the deprecated method also gives same error. Pls help..

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#37
