### ISSUE TITLE
JNA: "char*" always ends up as "Pointer" in callback apply() signature

### ISSUE THREAD

**Issue by FunkyM** [ochafik/nativelibs4java#513]
With some of the latest changes the "char*" to String conversion mapping improved quite a lot.

However, I've noticed that arguments in a callback's apply() signature are always Pointer, even for simple "char*" types.

Looking into JNADeclarationsConverter.java I noticed that there is apparently some type conversion mode not triggering within convertFunction():
```
boolean alternativeOutputs = !isCallback;
...
natFunc.addArg(new Arg(argName, typeConverter().convertTypeToJNA(mutType, TypeConversionMode.NativeParameter, libraryClassName)));
if (alternativeOutputs) {
    primOrBufFunc.addArg(new Arg(argName, typeConverter().convertTypeToJNA(mutType, TypeConversionMode.PrimitiveOrBufferParameter, libraryClassName)));
    natStructFunc.addArg(new Arg(argName, typeConverter().convertTypeToJNA(mutType, TypeConversionMode.NativeParameterWithStructsPtrPtrs, libraryClassName)));
}
...
```

If I change alternativeOutputs to always be true, the callback signature types correctly use "String" instead of "Pointer" making it much more convenient to work with inside the callback handlers.

Ift might also be worth to add such a test to "mixed callbacks.test":
```
typedef void* (*F4)(const char* cptr);
```

Working with git HEAD and generating JNA direct bindings.

**Comment by ochafik** [comment]
This issue was moved to ochafik/JNAerator#67
