### ISSUE TITLE
BridJ 0.7-SNAPSHOT gives segmentation error on IBM JRE

### ISSUE THREAD

**Issue by AndreasSandberg** [ochafik/nativelibs4java#514]
When trying to upgrade my BridJ libraries from 0.6.2 to the latest 0.7 snapshot I run into a segmentation fault using a IBM JRE. I have already used the 0.7 version on the same OS (Linux) running a Oracle JRE with success. I've tried to analyse the core dump and here are my findings so far:

The error is of type Segmentation error:

Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000004 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007FCCF33C29A0 Handler2=00007FCCF3061BD0 InaccessibleAddress=0000000000000010
...
/libj9vm26.so
Module_base_address=00007FCCF33A7000
Target=2_60_20140409_195732 (Linux 2.6.32-220.13.1.el6.x86_64)
CPU=amd64 (2 logical CPUs) (0xef927000 RAM)
Stack Backtrace 
(0x00007FCCF33DE24C [libj9vm26.so+0x3724c])

And the corresponding core txt file gives me;
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "main" J9VMThread:0x00000000224B0100, j9thread_t:0x00007FCCEC007BE0, java/lang/Thread:0x00000000025D9CF8, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0x7515, native priority:0x5, native policy:UNKNOWN)
3XMTHREADINFO2            (native stack address range from:0x00007FCCF3775000, to:0x00007FCCF4176000, size:0xA01000)
3XMCPUTIME               CPU usage total: 1.623299182 secs
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=718152 (0xAF548)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at org/bridj/JNI.bindJavaMethodsToCFunctions(Native Method)
4XESTACKTRACE                at org/bridj/NativeEntities.addDefinitions(NativeEntities.java:149)
4XESTACKTRACE                at org/bridj/CRuntime.register(CRuntime.java:468)
5XESTACKTRACE                   (entered lock: org/bridj/CRuntime@0x0000000002557DE0, entry count: 1)
4XESTACKTRACE                at org/bridj/CRuntime.register(CRuntime.java:345)
4XESTACKTRACE                at org/bridj/BridJ.register(BridJ.java:363)
4XESTACKTRACE                at org/bridj/BridJ.register(BridJ.java:203)
5XESTACKTRACE                   (entered lock: org/bridj/BridJ@0x00000000024CB1E8, entry count: 1)
4XESTACKTRACE                at .../jna/TbusLibrary.<clinit>(TbusLibrary.java:28)
4XESTACKTRACE                at java/lang/J9VMInternals.initializeImpl(Native Method)
4XESTACKTRACE                at java/lang/J9VMInternals.initialize(J9VMInternals.java:237(Compiled Code))

The IBM snap file indicates that the class org/bridj/CallIO is loaded before the error handling is invoked;

14:25:40.271491000          0x224b0100       j9vm.221  Event       sendInitialize - class org/bridj/CallIO
14:25:40.271493000          0x224b0100 j9bcverify.107  Entry      >j9bcv_verifyBytecodes - org/bridj/CallIO
14:25:40.271495000          0x224b0100 j9bcverify.50   Entry      >checkAllClassLoadingConstraints(ramClass=0x2270d500 -- org/bridj/CallIO)
14:25:40.271496000          0x224b0100 j9bcverify.111  Exit       <j9bcv_verifyBytecodes - returning 0
14:25:40.271502000          0x224b0100       j9vm.20   Entry      >sendClinit
14:25:40.271503000          0x224b0100       j9vm.21   Exit       <sendClinit (no <clinit> found)
14:25:40.271504000          0x224b0100       j9vm.315  Entry      >0X224b0100 loader 0x7fccec042ba8 class org/bridj/LastError arbitratedLoadClass enter className
14:25:40.271508000          0x224b0100       j9vm.119  Event       send loadClass(org/bridj/LastError), stringObject: 0x2238d1b0 loader: 0x25d64e8
14:25:40.271509000          0x224b0100       j9vm.28   Entry      >sendLoadClass
14:25:40.271519000          0x224b0100       j9vm.351  Entry      >loader 0x25d5f00 class org/bridj/LastError attemptDynamicClassLoad entry
14:25:40.271528000          0x224b0100       j9vm.353  Exit       <loader 0x0 class 0X7fccf41737e0 attemptDynamicClassLoad exit
14:25:40.271833000          0x224b0100 j9bcverify.14   Entry      >j9bcv_verifyClassStructure - class: org/bridj/LastError
14:25:40.271849000          0x224b0100 j9bcverify.18   Exit       <j9bcv_verifyClassStructure
14:25:40.271934000          0x224b0100       j9vm.1    Entry      >Create RAM class from ROM class 0x7fccec73e8d8 in class loader 0x7fccec042ba8
14:25:40.271936000          0x224b0100       j9vm.80   Event       ROM class 0x7fccec73e8d8 is named org/bridj/LastError

I'm not sure how to analyse this error further, I could probably add some debug logging but so far I haven't seen anything useful in my application logs.

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#38
