### ISSUE TITLE
Can't load bridj in Android Env.

### ISSUE THREAD

**Issue by wpoosanguansit** [ochafik/nativelibs4java#520]
Hi, 

I tried to use the library in Android but I get this error while try calling the addTwoInts method:

07-10 12:22:05.922    9413-9413/test W/System.err﹕ java.lang.RuntimeException: Failed to initialize BridJ (java.lang.UnsatisfiedLinkError: Couldn't load bridj from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/test-2.apk"],nativeLibraryDirectories=[/data/app-lib/test-2, /vendor/lib, /system/lib]]]: findLibrary returned null)

I have used both 0.7 snapshot and 0.63.  The code compiles correctly but throws up the run time exception as above.  Is there any setup needed other than including it in the libs?  Thanks for your help.

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#39
