### ISSUE TITLE
BridJ 0.7-SNAPSHOT 64 bit SunOs libbridj.so is actually a 32 bit binary (build error).

### ISSUE THREAD

**Issue by AndreasSandberg** [ochafik/nativelibs4java#529]
Hi!
When we tried to switch to 64 bit java we found that the bundled libbridj.so under org.bridj.lib.sunos_x64 is actually a 32 bit binary. Probably just an build error but either way it should be corrected.

BR!
// Andreas

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#41
