### ISSUE TITLE
Bridj sum two int return wrong

### ISSUE THREAD

**Issue by i2534** [ochafik/nativelibs4java#530]
I write a simple c++ code for test,like this:

#ifndef HELLO_H
#define HELLO_H

#define EXTERN_DLL_EXPORT extern "C" __declspec(dllexport)

class Hello
{
public:
    Hello(const int& a, const int& b);
    ~Hello();

    int Sum();

private:
    int a;
    int b;
};

EXTERN_DLL_EXPORT Hello* NewHello(int a, int b);
EXTERN_DLL_EXPORT int Sum(Hello* h);

#endif // HELLO_H

on windows 8,use qtcreator export to dll
then java code:

public interface JNAHelloLib extends StdCallLibrary {

		JNAHelloLib INSTANCE = (JNAHelloLib) Native.loadLibrary("hello",
				JNAHelloLib.class);

		com.sun.jna.Pointer NewHello(int a, int b);

		int Sum(com.sun.jna.Pointer p);
	}

	@Library("hello")
	public static class Hello extends CPPObject {
		static {
			BridJ.register();
		}

		/** Original signature : <code>Hello(const int&, const int&)</code> */
		@Constructor(0)
		public Hello(Pointer<Integer> a, Pointer<Integer> b) {
			super((Void) null, 0, a, b);
		}

		/**
		 * Original signature : <code>int Sum()</code><br>
		 * <i>native declaration : line 13</i>
		 */
		public native int Sum();

		@Field(0)
		public int a() {
			return this.io.getIntField(this, 0);
		}

		@Field(0)
		public Hello a(int a) {
			this.io.setIntField(this, 0, a);
			return this;
		}

		@Field(1)
		public int b() {
			return this.io.getIntField(this, 1);
		}

		@Field(1)
		public Hello b(int b) {
			this.io.setIntField(this, 1, b);
			return this;
		}
	}

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		JNAHelloLib h = JNAHelloLib.INSTANCE;
		System.out.println(h.Sum(h.NewHello(1, 2)));

		Pointer<Integer> a = Pointer.allocateInt();
		a.set(5);
		Pointer<Integer> b = Pointer.allocateInt();
		b.set(10);
		Hello h1 = new Hello(a, b);
		// h1.a(5);
		// h1.b(10);
		System.out.println(h1.a());
		System.out.println(h1.b());
		System.out.println(h1.Sum());
	}

output is :
3
0
0
1840125516

what happend?

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#42
