### ISSUE TITLE
Executable stack warning from JVM

### ISSUE THREAD

**Issue by shevek** [ochafik/nativelibs4java#541]
OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/BridJExtractedLibraries8475793964869801810/libbridj.so which might have disabled stack guard. The VM will try to fix the stack guard now.

I don't think I invoked BridJ. I got this from the gradle-jnaerator-plugin test suite. Why did it load a library I didn't execute?

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#45
