### ISSUE TITLE
Passing structures "by value"

### ISSUE THREAD

**Issue by ivangfr** [ochafik/nativelibs4java#554]
Hi,

I have a function with this signature:
```
int DeleteElement(FOO*, BAR, char, char);
```

However, when I execute it, I get a RuntimeException error: **"Failed to get low-level struct representation !"**

I implemented a second version of the function, now the second parameter is a pointer:
```
int DeleteElement2(FOO*, BAR*, char, char);
```
Now it works.

Googling about it, I found this (https://groups.google.com/forum/#!topic/nativelibs4java/Xj4Y-yTB8DI) when you said that

>"Unfortunately passing and returning structures "by value" (as opposed to "by reference" or "by pointer") is not supported by BridJ yet (the underlying dyncall library doesn't support them).
It's currently my top priority for BridJ". (1/9/13)

So, I would like to confirm if it's not implemented in the version 0.6.2? Do you plan to implement it in the next versions?

**Congratulations! It's a great project!**

Regards

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#46
