### ISSUE TITLE
unsigned long* is getting converted to Pointer<org.bridj.ann.CLong>

### ISSUE THREAD

**Issue by Abhaykumar1** [ochafik/nativelibs4java#555]
I'm very new to the BridJ. I used Jnaerator to generate the BridJ representations. For a unsigned long* the conversion is to Pointer <org.bridj.ann.CLong>. How do I create a pointer to org.bridj.ann.CLong, as I get compilation error cannot assign memory for org.bridj.ann.CLong

**Comment by Abhaykumar1** [comment]
I converted the generate code to Pointer<org.bridj.CLong> and things worked for me

**Comment by ochafik** [comment]
Hi @Abhaykumar1 ,

Sorry for the late reply, I'm glad you found a workaround!

For the record, `Pointer.pointerToCLong(123)` will create a `Pointer<CLong>` for you.

Cheers
