### ISSUE TITLE
Dll Demangle error in UnsatisfiedLinkError

### ISSUE THREAD

**Issue by xinjian0394** [ochafik/nativelibs4java#558]
Hi,
I'm trying BridJ  in win7 with JDK 1.7 32b vs08sp1 , and some UnsatisfiedLinkError occurred.
I thought this would be some bug while demangling DLL symbol.

here is some debug message example  that i think would help:

symbol="?paramtesta@Mytest@mydlltest@@QAEXHPADMPAVMyClass@2@@Z", 
demangled="void mydlltest.Mytest.paramtesta(int, byte*, float, 2.MyClass*)"
void paramtesta(int a, char* dtr, float f, MyClass* tmp);

symbol="?paramtestb@Mytest@mydlltest@@QAEXHPAVMyClass@2@PADM@Z", 
demangled="null ?paramtestb@Mytest@mydlltest@@QAEXHPAVMyClass@2@PADM@Z()"
void paramtestb(int a, MyClass* tmp, char* dtr, float f);

symbol="?paramstesta@Mytest@mydlltest@@QAEXHPADMPAVMyClass@2@1@Z", 
demangled="null ?paramstesta@Mytest@mydlltest@@QAEXHPADMPAVMyClass@2@1@Z()"
void paramstesta(int a, char* dtr, float f, MyClass* tmp1, MyClass* tmp2);

symbol="?paramstestb@Mytest@mydlltest@@QAEXHPADPAVMyClass@2@M1@Z", 
demangled="null ?paramstestb@Mytest@mydlltest@@QAEXHPADPAVMyClass@2@M1@Z()"
void paramstestb(int a, char* dtr, MyClass* tmp1, float f, MyClass* tmp2);

symbol="?paramstest2b@Mytest@mydlltest@@QAEXHPADPAVMyClass@2@MAAV32@@Z", 
demangled="void mydlltest.Mytest.paramstest2b(int, byte*, MAAV32.2.MyClass*)"
void paramstest2b(int a, char* dtr, MyClass* tmp1, float f, MyClass& tmp2);

symbol="?paramstest3b@Mytest@mydlltest@@QAEXHPADAAVMyClass@2@MPAV32@@Z", 
demangled="void mydlltest.Mytest.paramstest3b(int, byte*, MPAV32.2.MyClass&)"
void paramstest3b(int a, char* dtr, MyClass& tmp1, float f, MyClass* tmp2);

Please let me know if more info is needed.
Thanks a lot.

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#48
