### ISSUE TITLE
It's about time for a new JNAerator release

### ISSUE THREAD

**Issue by npiguet** [ochafik/nativelibs4java#560]
Version 0.11 was released over a year ago, and is incompatible with recent versions of JNA. 

Version 0.12-SNAPSHOT is compatible with recent versions of JNA, but is not released and cannot be found in the maven central repository (which causes all sorts of problems).

My usecase for that is: I've just started integrating JNAerator maven plugin into the build process of the libsass-maven-plugin. It works perfectly with version 0.12-SNAPSHOT, but fails to build with version 0.11.

**Comment by ochafik** [comment]
Alright, please try it while it's hot: 0.12 is in the wild for you to enjoy :-)

I'm now working on splitting JNAerator, BridJ and JavaCL to their own github repos, but please let me know of any issue with 0.12 so I can release a patch version quickly (i.e. in days/weeks rather than a year :-))

**Comment by npiguet** [comment]
Thanks :-)

**Comment by npiguet** [comment]
Well, first issue: You didn't tag the release changeset.

**Comment by ochafik** [comment]
Oops, thanks!

Done in legacy http://github.com/ochafik/nativelibs4java repo and in shiny-new split repo http://github.com/ochafik/JNAerator
